Added reminder creation feedback
TeamOctolings/Boyfriend pull request #24
Opened 2023-02-01 18:51 UTC by mctaylors

2023-02-01 19:26 UTC, Octol1ttle requested changes

2023-02-01 19:26 UTC, Octol1ttle commented on Commands/RemindCommand.cs
> +            var feedback = string.Format(Messages.FeedbackReminderAdded, DateTimeOffset.Now.Add(remindIn).ToUnixTimeSeconds());
`Boxing allocation: conversion from 'long' to 'object' requires boxing of the value type`

Use `ToString()` to avoid this allocation (ignore GitHub code scanning)

2023-02-01 19:26 UTC, Octol1ttle commented on Commands/RemindCommand.cs
>          cmd.ConfigWriteScheduled = true;
Put this in the `if` block above to avoid unnecessary config writes

2023-02-01 19:26 UTC, Octol1ttle commented on Commands/RemindCommand.cs
> +            var feedback = string.Format(Messages.FeedbackReminderAdded, DateTimeOffset.Now.Add(remindIn).ToUnixTimeSeconds());
Calling `DateTimeOffset.Now` repeatedly has a performance impact (and adding probably does too). Store `RemindAt` in a variable to avoid that (don't store the entire Reminder as that will cause struct copying).

2023-02-01 19:26 UTC, Octol1ttle commented on Commands/RemindCommand.cs
> +            cmd.Audit(feedback);
Why is the reminder creation feedback being audited?

2023-02-01 19:26 UTC, Octol1ttle commented on Commands/RemindCommand.cs
> +            cmd.Reply(feedback, ReplyEmojis.Success);
Consider adding and using a different emoji for this (maybe an alarm?)

2023-02-01 19:29 UTC, mctaylors commented on Commands/RemindCommand.cs
> +            var feedback = string.Format(Messages.FeedbackReminderAdded, DateTimeOffset.Now.Add(remindIn).ToUnixTimeSeconds());
ok

2023-02-01 19:33 UTC, mctaylors commented on Commands/RemindCommand.cs
> +            cmd.Audit(feedback);
lol i just copied that from ban command and forgot to remove it

2023-02-02 04:44 UTC, Octol1ttle approved these changes

2023-02-02 04:48 UTC, merged