The Milestone Commit
TeamOctolings/Boyfriend pull request #48
Opened 2023-07-09 18:27 UTC by mctaylors

2023-07-13 11:43 UTC, Octol1ttle requested changes

2023-07-13 11:43 UTC, Octol1ttle commented on docs/README.md
> +<img src="https://github.com/TeamOctolings/Boyfriend/blob/milestone-commit/docs/assets/boyfriend-light.png#gh-dark-mode-only"
This hardcodes the logo images to this branch of this repository of this organization. Not ideal.

2023-07-13 11:43 UTC, Octol1ttle commented on docs/assets/boyfriend-dark.png
Why have the logos been turned to their oversimplified versions?

2023-07-13 13:14 UTC, mctaylors commented on docs/assets/boyfriend-dark.png
because yes

2023-07-13 18:04 UTC, mctaylors commented on docs/README.md
> +<img src="https://github.com/TeamOctolings/Boyfriend/blob/milestone-commit/docs/assets/boyfriend-light.png#gh-dark-mode-only"
i'll fix that tomorrow

2023-07-15 15:11 UTC, mctaylors commented on docs/README.md
> +<img src="https://github.com/TeamOctolings/Boyfriend/blob/milestone-commit/docs/assets/boyfriend-light.png#gh-dark-mode-only"
ok maybe on monday (i love my internet providers)

2023-07-18 04:56 UTC, Octol1ttle requested changes

2023-07-18 04:56 UTC, Octol1ttle commented on src/Responders/MessageReceivedResponder.cs
> +                "пон" => "https://cdn.upload.systems/uploads/2LNfUSwM.jpg",
https://github.com/TeamOctolings/Boyfriend/blob/milestone-commit/src/Commands/AboutCommandGroup.cs#L70

2023-07-18 04:56 UTC, Octol1ttle commented on src/Responders/MessageReceivedResponder.cs
> +            gatewayEvent.ChannelID, ct: ct, content: gatewayEvent.Content.ToLower() switch {
Please use `.ToLowerInvariant()`

2023-07-18 09:02 UTC, Octol1ttle submitted a review, later dismissed

2023-07-18 12:24 UTC, Octol1ttle approved these changes

2023-07-18 12:27 UTC, merged